spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
queue:
  endpoint: https://sqs.ap-northeast-1.amazonaws.com/

bucket:
  name: debugroom-sample
s3:
  upload:
    role:
      name: sample-s3-access-role
      session:
        name: sample
  download:
    role:
      name: sample-s3-access-role
      session:
        name: sample
    durationseconds: 600